"""Temporary file lifecycle management.

Every job gets its own directory under TEMP_DIR/<job_id>/. This module
removes that directory on success, failure, and timeout, and provides a
periodic sweep for orphaned directories left behind by a worker crash.
"""

from __future__ import annotations

import shutil
import time
from pathlib import Path

from core.logging import get_logger

logger = get_logger(component="cleanup")


def job_dir_for(temp_dir: Path, job_id: str) -> Path:
    # job_id is always a uuid4 hex generated by us — never derived from
    # user input — but sanitize defensively anyway.
    safe_id = "".join(c for c in job_id if c.isalnum() or c == "-")
    return temp_dir / safe_id


def cleanup_job_dir(temp_dir: Path, job_id: str) -> None:
    path = job_dir_for(temp_dir, job_id)
    if not path.exists():
        return
    try:
        shutil.rmtree(path, ignore_errors=True)
        logger.info("cleanup_completed", job_id=job_id)
    except OSError as exc:
        logger.warning("cleanup_failed", job_id=job_id, error=str(exc))


def sweep_orphaned_dirs(temp_dir: Path, *, max_age_seconds: int) -> int:
    """Delete job directories older than max_age_seconds. Returns count removed.

    Called periodically by the worker to recover from crashes that skipped
    normal cleanup (e.g. SIGKILL mid-job).
    """

    if not temp_dir.exists():
        return 0

    removed = 0
    now = time.time()
    for entry in temp_dir.iterdir():
        if not entry.is_dir():
            continue
        try:
            age = now - entry.stat().st_mtime
        except OSError:
            continue
        if age > max_age_seconds:
            shutil.rmtree(entry, ignore_errors=True)
            removed += 1
            logger.info("orphan_cleanup", directory=str(entry), age_seconds=int(age))
    return removed


def total_temp_usage_bytes(temp_dir: Path) -> int:
    if not temp_dir.exists():
        return 0
    total = 0
    for entry in temp_dir.rglob("*"):
        if entry.is_file():
            try:
                total += entry.stat().st_size
            except OSError:
                continue
    return total
